### ISSUE TITLE
Uninitialized constant error when trying to include Model or Representer in a Trailblazer::Operation (Grape)

### ISSUE THREAD

**Issue by michaellennox** [trailblazer/trailblazer#141]
I'm currently building a small API in Grape with Trailblazer and Sequel, taking inspiration from the grape-gemgem repo.

Unfortunately within the Trailblazer::Operation the Representer and Model constants, (infact all the constants that i think? would be loaded in rails https://github.com/trailblazer/trailblazer/blob/master/lib/trailblazer/autoloading.rb) do not appear to be present within my grape environment and as such when it is loaded (using Trailblazer::Loader) gem I get uninitialized constant errors.

Versions

ruby 2.3.1

trailblazer v1.1.1
trailblazer-loader v0.1.0
grape v0.18.0

I can't open up the repo unfortunately but below are some snippets from the main application file and the operation.

```
# gannet.rb
require 'grape'
require 'trailblazer'
require 'trailblazer/loader'
require 'reform/form/active_model/validations'

# require the database configuration
require_relative 'config/database'

class Gannet < Grape::API
  format :json

  resource :merchants do
    post { run!(Merchant::Create, request) }
  end

  helpers do
    def run!(operation_klass, request)
      params = JSON.parse(request.body.read)

      operation_klass.(params).to_json
    end
  end
end

Reform::Form.class_eval do
  include Reform::Form::ActiveModel::Validations
end

Trailblazer::Loader.new.(concepts_root: './lib/concepts/', debug: true) { |file| require_relative file }
```

```
# lib/concepts/merchant/operation.rb
class Merchant::Create < Trailblazer::Operation
  include Representer # this raises error

  contract do
    property :name, validates: {presence: true}
    property :code, validates: {presence: true}
  end

  representer do
    include Roar::JSON
  end

  def process(params)
    @model = Merchant.new

    validate(params[:merchant], @model) do |f|
      f.save
    end
  end
end
```

The stack trace from when an error is raised:

```
michaellennox@Michaels-MacBook-Pro:~/Projects/gannet% rackup
["./lib/concepts/merchant/model.rb", "./lib/concepts/merchant/operation.rb"]
/Users/michaellennox/Projects/gannet/lib/concepts/merchant/operation.rb:2:in `<class:Create>': uninitialized constant Merchant::Create::Representer (NameError)
Did you mean?  Representable
	from /Users/michaellennox/Projects/gannet/lib/concepts/merchant/operation.rb:1:in `<top (required)>'
	from /Users/michaellennox/Projects/gannet/gannet.rb:33:in `require_relative'
	from /Users/michaellennox/Projects/gannet/gannet.rb:33:in `block in <top (required)>'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:75:in `block in load_files'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:75:in `each'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:75:in `load_files'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/trailblazer-loader-0.1.0/lib/trailblazer/loader.rb:38:in `call'
	from /Users/michaellennox/Projects/gannet/gannet.rb:33:in `<top (required)>'
	from /Users/michaellennox/Projects/gannet/config.ru:4:in `require_relative'
	from /Users/michaellennox/Projects/gannet/config.ru:4:in `block in <main>'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
	from /Users/michaellennox/Projects/gannet/config.ru:in `new'
	from /Users/michaellennox/Projects/gannet/config.ru:in `<main>'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/server.rb:282:in `start'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/lib/rack/server.rb:147:in `start'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/gems/rack-2.0.1/bin/rackup:4:in `<top (required)>'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/bin/rackup:23:in `load'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/bin/rackup:23:in `<main>'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michaellennox/.rvm/gems/ruby-2.3.1@gannet/bin/ruby_executable_hooks:15:in `<main>'
```

If I call `Merchant::Create.constants` during loading I get the following:

```
    1: class Merchant::Create < Trailblazer::Operation
    2:   require 'byebug'; byebug;
=>  3:   include Representer
    4:
    5:   contract do
    6:     property :name, validates: {presence: true}
    7:     property :code, validates: {presence: true}
    8:   end
    9:   # require 'byebug'; byebug;
   10:   representer do
(byebug) Merchant::Create.constants
[:Builder, :Setup, :InvalidContract, :Constant, :ClassMethods]
```

It would appear the loading hasn't happened properly, is this something I need to configure and make happen myself or something that should be 'just happening' (and if so, is it something you could provide some pointers on so I could look at contributing it back)?

As always, thanks for all your work on Trailblazer, it's a real pleasure to work with in other environments but this is the first time I'm trying to make use of it with Grape so it could be I'm doing something stupid.

**Comment by apotonick** [comment]
Autoloading is removed from 2.0 and instead we simply load everything upfront (as Matz and Hiroshi recommend).

Without Rails, the autoloading doesn't work, so it's up to you to load things. :wink:

**Comment by gerrywastaken** [comment]
For anybody else here from google, it might be that you are trying to load a constant called `TrailBlazer` instead of `Trailblazer` (small "b"). Figure this might save somebody a bit of time one day.
