### ISSUE TITLE
Using trailblazer with a mountable engine

### ISSUE THREAD

**Issue by yurifrl** [trailblazer/trailblazer#71]
I'm having trouble using trb with a mountable engine, i'm getting a error like https://github.com/apotonick/trailblazer/issues/30 
Here's my code:

Here is my controller, i included everything from the sample app

``` ruby
# Controller
# spree_reports/app/controllers/spree/admin/fine_reports_controller.rb
module Spree
  module Admin
    class FineReportsController < Spree::Admin::ReportsController
      include Trailblazer::Operation::Controller
      require 'trailblazer/operation/controller/active_record'
      include Trailblazer::Operation::Controller::ActiveRecord # named instance variables.

      def best_selling
        # ERROR
        # uninitialized constant Report::Index
        collection ::Report::Index
        # i will figure this out latter
        @cell = "report/cells/best_selling"
      end
    end
  end
end
```

The concept

``` ruby
# Crud
# spree_reports/app/concepts/report/crud.rb
class Report < ActiveRecord::Base
  class Index < Trailblazer::Operation
    include Collection

    def model!(params)
      # I just want to stop here
      byebug
    end
  end
end
```

Here is the initializers, i looked at trb and required some things

``` ruby
# spree_reports/config/initializers/trailblazer.rb
require 'trailblazer'
require 'trailblazer/autoloading'
require "trailblazer/rails/railtie"

# require 'trailblazer/responder'
# Trailblazer::Operation::CRUD.module_eval do
#   module Included
#     def included(base)
#       super # the original CRUD::included method.
#       base.send :include, Trailblazer::Operation::CRUD::ActiveModel
#     end
#   end
#   extend Included # override CRUD::included.
# end
```

My stack trace

``` ruby
Started GET "/admin/reports/best_selling" for 127.0.0.1 at 2015-08-13 16:37:11 -0300
  Requested URL: https://test.lvh.me/admin/reports/best_selling, subdomain: test, host: test.lvh.me
Processing by Spree::Admin::FineReportsController#best_selling as HTML
Completed 500 Internal Server Error in 18ms (ActiveRecord: 2.1ms)
** [Raven] Event not sent due to excluded environment: development

NameError (uninitialized constant Report::Index):
  /home/yuri/workspace/rails/plugins/spree_reports/app/controllers/spree/admin/fine_reports_controller.rb:24:in `best_selling'
  actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.2) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.2) lib/active_support/callbacks.rb:313:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  /home/yuri/.rvm/gems/ruby-2.1.1/bundler/gems/route_translator-e62be7f48c77/lib/route_translator/extensions/action_controller.rb:20:in `set_locale_from_url'
  activesupport (4.2.2) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.2) lib/active_support/callbacks.rb:312:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.2) lib/active_support/callbacks.rb:497:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  /home/yuri/.rvm/gems/ruby-2.1.1/bundler/gems/apartment-5e7ebbedabfd/lib/apartment/reloader.rb:18:in `call'
  /home/yuri/workspace/rails/plugins/spree_shared/lib/spree_shared/apartment_elevator.rb:37:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.2) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  /home/yuri/.rvm/gems/ruby-2.1.1/bundler/gems/web-console-5a4c0c495813/lib/web_console/middleware.rb:40:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /home/yuri/.rvm/gems/ruby-2.1.1/bundler/gems/rack-dev-mark-1152d3d74e2c/lib/rack/dev-mark/middleware.rb:17:in `call'
  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  chewy (0.8.1) lib/chewy/railtie.rb:16:in `block in call'
  chewy (0.8.1) lib/chewy/strategy.rb:54:in `wrap'
  chewy (0.8.1) lib/chewy.rb:160:in `strategy'
  chewy (0.8.1) lib/chewy/railtie.rb:16:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  sentry-raven (0.13.3) lib/raven/integrations/rack.rb:54:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/application.rb:164:in `call'
  puma (2.9.1) lib/puma/rack_patch.rb:13:in `call'
  sinatra (1.4.6) lib/sinatra/base.rb:218:in `call'
  puma (2.9.1) lib/puma/configuration.rb:71:in `call'
  puma (2.9.1) lib/puma/server.rb:490:in `handle_request'
  puma (2.9.1) lib/puma/server.rb:361:in `process_client'
  puma (2.9.1) lib/puma/server.rb:254:in `block in run'
  puma (2.9.1) lib/puma/thread_pool.rb:92:in `call'
  puma (2.9.1) lib/puma/thread_pool.rb:92:in `block in spawn_thread'

```

unless I'm using spree, I don't think there is more information i can provide, glad if someone can help.

**Comment by fernandes** [comment]
check my comment on #30 after crud.rb being loaded this problem will be fixed

**Comment by apotonick** [comment]
Please open in Trailblazer-rails if the problem still exists. Thanks!

https://github.com/trailblazer/trailblazer-rails/issues
